### ISSUE TITLE
ne LeBlanc avail?

### ISSUE THREAD

**Issue by Kiruscha** [Sizzzles/TFT-OCR-BOT#1]
Hello,
auto comp doesnt pull up any comps containing LeBlanc. Why is that?
Can you add her?

**Comment by Sizzzles** [comment]
Comps are pulled from [https://lolchess.gg/meta](url). I can see there is one comp that has LeBlanc with the name Annie Zoe LeBlanc
I will note it doesn't seem to pull all the comps. I am currently trying to figure this out as I learn the code

**Comment by Sizzzles** [comment]
Looked into the auto comps and the bot removes incomplete comps that aren't pulled correctly from lolchess.gg so you aren't playing a comp that is incomplete or isn't a comp at all hence why some comps that show on lolchess.gg aren't being pulled. This could be a coding issue or site issue... Most likely a coding issue as I'm sure the site has updated since auto comps were implemented.

All that being said I'm just going to close this and look into it more when I can as I'm currently working on other things with the bot at this time
