### ISSUE TITLE
Why does this crash?

### ISSUE THREAD

**Issue by FrapzHaash** [Sizzzles/TFT-OCR-BOT#25]
![mc-Untitled](https://github.com/Sizzzles/TFT-OCR-BOT/assets/80805708/7803efe1-6773-4c3d-bea1-b1844650d8d1)
works some games and then crashes

**Comment by Sizzzles** [comment]
Because the comp being used is using units that don't have tiers (stars) so comps that include T-Hex, Apex Turret, Void Remora, Rift Herald, Baron. These comps shouldn't be used anyway since the bot doesn't have logic for them and results with units not being placed correctly since T-Hex or whatever is in the spot it wants to place an actual champion. I don't plan to add logic for these since there will be something different by next set

Just exclude comps that have non-champion units from your selection

**Comment by Sizzzles** [comment]
This has been fixed the the newest update. You can use summon unit comps again
