### ISSUE TITLE
Still not picking augments on 2-1

### ISSUE THREAD

**Issue by loweluis** [Sizzzles/TFT-OCR-BOT#3]
I don't know if its because im using 1366x768 resolution but its still not picking augments at 2-1 and the console is just spamming comps, and just like last time the bot comes back at 3-1 but when the game loses when im at 0 hp the bot doesnt exit and it will spectate the ongoing match until the end.

![00bfd208a1f117f348bb199d94937725](https://user-images.githubusercontent.com/28964712/217927583-58503f72-2063-43eb-b023-9f847576cc6b.png)

**Comment by Sizzzles** [comment]
From my experience your resolution should be 1920x1080 at minimum. If you are running a laptop you'll most likely need to set your scaling to 100% which is found in your windows display settings.
My resolution 2560x1440 but my in game resolution is 1920x1080 and from my testing I haven't had any problems

**Comment by loweluis** [comment]
> By chance do you have the same problem with the original [TFT-OCR-BOT](https://github.com/jfd02/TFT-OCR-BOT)?
yes I do, it also stops at 2-1 and continues at 3-1

**Comment by loweluis** [comment]
I'm actually okay with it not playing properly, I just want the bot to leave at death and replay to farm afk.

**Comment by Sizzzles** [comment]
> yes I do, it also stops at 2-1 and continues at 3-1

Okay so the original bot leaves the game after death, correct?

**Comment by loweluis** [comment]
> > yes I do, it also stops at 2-1 and continues at 3-1
> 
> Okay so the original bot leaves the game after death, correct?

It doesn't leave the game after death either, it also says cant detect health or something like that so it will just continue to watch the game even after death.

**Comment by Sizzzles** [comment]
Did a little testing with the original [TFT-OCR-BOT](https://github.com/jfd02/TFT-OCR-BOT) and this version looks like a resolution issue. From my understanding the bot is made for a minimum resolution of 1920x1080 since I couldn't get it to work correctly on any lower resolution.
Not picking augments at 2-1 then coming back at 3-1 also not exiting game when at 0 hp (exactly what you are experiencing) but once resolution is changed to 1920x1080 both versions work flawlessly.

If you want to use the bot to farm you can try changing `FORFEIT = False` to `FORFEIT = True` in settings.py via notepad or any text editor

**Comment by loweluis** [comment]
Thanks for the help
