### ISSUE TITLE
Support for languages ​​other than English 🌐

### ISSUE THREAD

**Issue by LucasBonafe** [Sizzzles/TFT-OCR-BOT#41]
[Notes](https://github.com/Sizzzles/TFT-OCR-BOT#notes) says:
> League & client must be in English.

I want to change this, how can I get character and item names in other languages ​​and put a `switch case` for automatic language definition?

I noticed that there are 2 files with names, but I need help implementing a system that understands which language the game is in and defines the files correctly.

**Comment by LucasBonafe** [comment]
What about creating different queue types?
https://github.com/Sizzzles/TFT-OCR-BOT/blob/74bcd6c5815698a0bc10ad0502109c97c0c5fb24/auto_queue.py#L32

As in the example:
https://github.com/RiotGames/developer-relations/issues/574

**Comment by Sizzzles** [comment]
I have very little knowledge on different tft game modes but I'm assuming they would need extra logic for example hyper roll has a completely different system than normal games and double up has the whole sending your teammate units. I'm not adapting the bot for this.

The whole idea of the bot is just to farm the pass. I wouldn't even try the bot in ranked because you will get the lowest rank
This isn't a competitive bot. It's a I'm too lazy to play tft games myself and want rewards bot lol

**Comment by Sizzzles** [comment]
I also find it hard enough to work on the bot as it is due to not having much free time so adding logic for other gamemodes is unrealistic for me currently, sorryyyy

Most of the bot updates are matching the original bot or fixing the auto comps due to site updates breaking it and I'll sometimes think of something new but that's rare
