### ISSUE TITLE
adds non valid champ

### ISSUE THREAD

**Issue by garbagexbag** [Sizzzles/TFT-OCR-BOT#6]
on round between 1-2 and 1-4 included the bot thinks it adds an unknown champ to the board while it actually adds nothing, which leads to it thinking for major part of the game it has one more champ on the board than it actually does. this does not seem to happen on the main branch this was forked from

**Comment by Sizzzles** [comment]
I've never had this issue. But increased sleep between clicks for unknown champions. Let me know if it fixes the issue

**Comment by Sizzzles** [comment]
Okay perfect.

I know what you mean and completely understand. I would love to fix this since I've noticed the same thing and have been frustrated with it but the main problem would be making sure it sells the champion the right champion especially if it's being used to hold items for a champion in the comp. I can see problems since it's pulling the latest comps from a site so having static fillers champs would be a problem for the 'dynamic' comps. I also don't have as much free time as I once did so it's hard for me to implement new logic like this.... But hopefully it can be worked on in the future.
